# This is a config for E2B sandbox template.
# You can use template ID (c1safcgsw5dp4ghv37lo) or template name (vibe-nextjs-sungwun-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-sungwun-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-sungwun-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-sungwun-2')

team_id = "d7007ee4-1cf7-40d6-a09e-1a8e898bf261"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-sungwun-2"
template_id = "c1safcgsw5dp4ghv37lo"
